module.exports = {
  USER_REGISTERED: 'user.registered',
  USER_LOGGED_IN: 'user.logged_in',
  GROUP_CREATED: 'group.created',
  CONVERSATION_CREATED: 'conversation.created',
  MESSAGE_SENT: 'message.sent',
  MESSAGE_EDITED: 'message.edited',
  MESSAGE_DELETED: 'message.deleted',
  MESSAGE_PINNED: 'message.pinned',
  MESSAGE_UNPINNED: 'message.unpinned',
  MESSAGE_REACTED: 'message.reacted',
  NOTIFICATION_CREATED: 'notification.created',
  FILE_UPLOADED: 'file.uploaded',
  PRESENCE_CHANGED: 'presence.changed',

  USER_BANNED: 'user.banned',
  USER_UNBANNED: 'user.unbanned',
  USER_MUTED: 'user.muted',
  USER_UNMUTED: 'user.unmuted',
  ADMIN_ADDED: 'admin.added',
  ADMIN_REMOVED: 'admin.removed',
  ADMIN_ACCESS_LEVEL_CHANGED: 'admin.access_level_changed',
  ADMIN_PRESENCE_VISIBILITY_CHANGED: 'admin.presence_visibility_changed',

  USERNAME_SET: 'user.username_set',
  PHONE_VERIFICATION_REQUESTED: 'user.phone_verification_requested',
  PHONE_VERIFIED: 'user.phone_verified',
  PASSWORD_RESET_REQUESTED: 'user.password_reset_requested',
  PASSWORD_RESET_COMPLETED: 'user.password_reset_completed',
  SESSION_REVOKED: 'session.revoked',
  SESSIONS_REVOKED_ALL: 'session.revoked_all',

  SETTINGS_UPDATED: 'settings.updated',

  ROOM_DELETED: 'room.deleted',
  ROOM_UPDATED: 'room.updated',
  ROOM_MEMBER_REMOVED: 'room.member_removed',
  ROOM_MEMBER_ROLE_CHANGED: 'room.member_role_changed',
  ROOM_INVITE_CREATED: 'room.invite_created',
  ROOM_INVITE_ACCEPTED: 'room.invite_accepted',
  ROOM_INVITE_REJECTED: 'room.invite_rejected',
  ROOM_INVITE_LINK_CREATED: 'room.invite_link_created',
  ROOM_JOINED_VIA_LINK: 'room.joined_via_link',

  USER_BLOCKED: 'user.blocked',
  USER_UNBLOCKED: 'user.unblocked',
  USER_MUTED_BY_USER: 'user.muted_by_user',
  USER_UNMUTED_BY_USER: 'user.unmuted_by_user',

  BROADCAST_SENT: 'broadcast.sent',
  BACKUP_CREATED: 'backup.created',
  BACKUP_DOWNLOADED: 'backup.downloaded',
  BACKUP_DELETED: 'backup.deleted',
  BACKUP_RESTORED: 'backup.restored'
};
